# Databricks App Configuration for Image-to-Image Editor
command: ["uvicorn", "backend.main:app"]

env:
  - name: ENV
    value: production
  - name: MLFLOW_EXPERIMENT_ID
    value: "3582259051905164"
  - name: MODEL_ENDPOINT_TOKEN
    valueFrom: "secret"
  - name: MODEL_ENDPOINT_URL
    valueFrom: "serving-endpoint"
